/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/main'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RetencaoVisualIndexRouteImport } from './routes/retencao-visual/index'
import { Route as PortuguesIndexRouteImport } from './routes/portugues/index'
import { Route as LogicoIndexRouteImport } from './routes/logico/index'
import { Route as EntrevistaIndexRouteImport } from './routes/entrevista/index'
import { Route as RetencaoVisualTesteRouteImport } from './routes/retencao-visual/teste'
import { Route as PortuguesPreviewRouteImport } from './routes/portugues/preview'
import { Route as PortuguesGravarRouteImport } from './routes/portugues/gravar'
import { Route as LogicoPreviewRouteImport } from './routes/logico/preview'
import { Route as LogicoIntroRouteImport } from './routes/logico/intro'
import { Route as EntrevistaPreviewRouteImport } from './routes/entrevista/preview'
import { Route as EntrevistaGravarRouteImport } from './routes/entrevista/gravar'
import { Route as SelectionProcessCandidateIdIndexRouteImport } from './routes/selection-process/$candidateId/index'
import { Route as SelectionProcessCandidateIdQuestionarioIndexRouteImport } from './routes/selection-process/$candidateId/questionario/index'
import { Route as SelectionProcessCandidateIdPortuguesIndexRouteImport } from './routes/selection-process/$candidateId/portugues/index'
import { Route as SelectionProcessCandidateIdQuestionarioIntroRouteImport } from './routes/selection-process/$candidateId/questionario/intro'
import { Route as SelectionProcessCandidateIdPortuguesPreviewRouteImport } from './routes/selection-process/$candidateId/portugues/preview'
import { Route as SelectionProcessCandidateIdPortuguesGravarRouteImport } from './routes/selection-process/$candidateId/portugues/gravar'

const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetencaoVisualIndexRoute = RetencaoVisualIndexRouteImport.update({
  id: '/retencao-visual/',
  path: '/retencao-visual/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortuguesIndexRoute = PortuguesIndexRouteImport.update({
  id: '/portugues/',
  path: '/portugues/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogicoIndexRoute = LogicoIndexRouteImport.update({
  id: '/logico/',
  path: '/logico/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistaIndexRoute = EntrevistaIndexRouteImport.update({
  id: '/entrevista/',
  path: '/entrevista/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetencaoVisualTesteRoute = RetencaoVisualTesteRouteImport.update({
  id: '/retencao-visual/teste',
  path: '/retencao-visual/teste',
  getParentRoute: () => rootRouteImport,
} as any)
const PortuguesPreviewRoute = PortuguesPreviewRouteImport.update({
  id: '/portugues/preview',
  path: '/portugues/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PortuguesGravarRoute = PortuguesGravarRouteImport.update({
  id: '/portugues/gravar',
  path: '/portugues/gravar',
  getParentRoute: () => rootRouteImport,
} as any)
const LogicoPreviewRoute = LogicoPreviewRouteImport.update({
  id: '/logico/preview',
  path: '/logico/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LogicoIntroRoute = LogicoIntroRouteImport.update({
  id: '/logico/intro',
  path: '/logico/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistaPreviewRoute = EntrevistaPreviewRouteImport.update({
  id: '/entrevista/preview',
  path: '/entrevista/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistaGravarRoute = EntrevistaGravarRouteImport.update({
  id: '/entrevista/gravar',
  path: '/entrevista/gravar',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionProcessCandidateIdIndexRoute =
  SelectionProcessCandidateIdIndexRouteImport.update({
    id: '/selection-process/$candidateId/',
    path: '/selection-process/$candidateId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelectionProcessCandidateIdQuestionarioIndexRoute =
  SelectionProcessCandidateIdQuestionarioIndexRouteImport.update({
    id: '/selection-process/$candidateId/questionario/',
    path: '/selection-process/$candidateId/questionario/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelectionProcessCandidateIdPortuguesIndexRoute =
  SelectionProcessCandidateIdPortuguesIndexRouteImport.update({
    id: '/selection-process/$candidateId/portugues/',
    path: '/selection-process/$candidateId/portugues/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelectionProcessCandidateIdQuestionarioIntroRoute =
  SelectionProcessCandidateIdQuestionarioIntroRouteImport.update({
    id: '/selection-process/$candidateId/questionario/intro',
    path: '/selection-process/$candidateId/questionario/intro',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelectionProcessCandidateIdPortuguesPreviewRoute =
  SelectionProcessCandidateIdPortuguesPreviewRouteImport.update({
    id: '/selection-process/$candidateId/portugues/preview',
    path: '/selection-process/$candidateId/portugues/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelectionProcessCandidateIdPortuguesGravarRoute =
  SelectionProcessCandidateIdPortuguesGravarRouteImport.update({
    id: '/selection-process/$candidateId/portugues/gravar',
    path: '/selection-process/$candidateId/portugues/gravar',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/interview': typeof InterviewRoute
  '/main': typeof MainRoute
  '/entrevista/gravar': typeof EntrevistaGravarRoute
  '/entrevista/preview': typeof EntrevistaPreviewRoute
  '/logico/intro': typeof LogicoIntroRoute
  '/logico/preview': typeof LogicoPreviewRoute
  '/portugues/gravar': typeof PortuguesGravarRoute
  '/portugues/preview': typeof PortuguesPreviewRoute
  '/retencao-visual/teste': typeof RetencaoVisualTesteRoute
  '/entrevista': typeof EntrevistaIndexRoute
  '/logico': typeof LogicoIndexRoute
  '/portugues': typeof PortuguesIndexRoute
  '/retencao-visual': typeof RetencaoVisualIndexRoute
  '/selection-process/$candidateId': typeof SelectionProcessCandidateIdIndexRoute
  '/selection-process/$candidateId/portugues/gravar': typeof SelectionProcessCandidateIdPortuguesGravarRoute
  '/selection-process/$candidateId/portugues/preview': typeof SelectionProcessCandidateIdPortuguesPreviewRoute
  '/selection-process/$candidateId/questionario/intro': typeof SelectionProcessCandidateIdQuestionarioIntroRoute
  '/selection-process/$candidateId/portugues': typeof SelectionProcessCandidateIdPortuguesIndexRoute
  '/selection-process/$candidateId/questionario': typeof SelectionProcessCandidateIdQuestionarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/interview': typeof InterviewRoute
  '/main': typeof MainRoute
  '/entrevista/gravar': typeof EntrevistaGravarRoute
  '/entrevista/preview': typeof EntrevistaPreviewRoute
  '/logico/intro': typeof LogicoIntroRoute
  '/logico/preview': typeof LogicoPreviewRoute
  '/portugues/gravar': typeof PortuguesGravarRoute
  '/portugues/preview': typeof PortuguesPreviewRoute
  '/retencao-visual/teste': typeof RetencaoVisualTesteRoute
  '/entrevista': typeof EntrevistaIndexRoute
  '/logico': typeof LogicoIndexRoute
  '/portugues': typeof PortuguesIndexRoute
  '/retencao-visual': typeof RetencaoVisualIndexRoute
  '/selection-process/$candidateId': typeof SelectionProcessCandidateIdIndexRoute
  '/selection-process/$candidateId/portugues/gravar': typeof SelectionProcessCandidateIdPortuguesGravarRoute
  '/selection-process/$candidateId/portugues/preview': typeof SelectionProcessCandidateIdPortuguesPreviewRoute
  '/selection-process/$candidateId/questionario/intro': typeof SelectionProcessCandidateIdQuestionarioIntroRoute
  '/selection-process/$candidateId/portugues': typeof SelectionProcessCandidateIdPortuguesIndexRoute
  '/selection-process/$candidateId/questionario': typeof SelectionProcessCandidateIdQuestionarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/interview': typeof InterviewRoute
  '/main': typeof MainRoute
  '/entrevista/gravar': typeof EntrevistaGravarRoute
  '/entrevista/preview': typeof EntrevistaPreviewRoute
  '/logico/intro': typeof LogicoIntroRoute
  '/logico/preview': typeof LogicoPreviewRoute
  '/portugues/gravar': typeof PortuguesGravarRoute
  '/portugues/preview': typeof PortuguesPreviewRoute
  '/retencao-visual/teste': typeof RetencaoVisualTesteRoute
  '/entrevista/': typeof EntrevistaIndexRoute
  '/logico/': typeof LogicoIndexRoute
  '/portugues/': typeof PortuguesIndexRoute
  '/retencao-visual/': typeof RetencaoVisualIndexRoute
  '/selection-process/$candidateId/': typeof SelectionProcessCandidateIdIndexRoute
  '/selection-process/$candidateId/portugues/gravar': typeof SelectionProcessCandidateIdPortuguesGravarRoute
  '/selection-process/$candidateId/portugues/preview': typeof SelectionProcessCandidateIdPortuguesPreviewRoute
  '/selection-process/$candidateId/questionario/intro': typeof SelectionProcessCandidateIdQuestionarioIntroRoute
  '/selection-process/$candidateId/portugues/': typeof SelectionProcessCandidateIdPortuguesIndexRoute
  '/selection-process/$candidateId/questionario/': typeof SelectionProcessCandidateIdQuestionarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/interview'
    | '/main'
    | '/entrevista/gravar'
    | '/entrevista/preview'
    | '/logico/intro'
    | '/logico/preview'
    | '/portugues/gravar'
    | '/portugues/preview'
    | '/retencao-visual/teste'
    | '/entrevista'
    | '/logico'
    | '/portugues'
    | '/retencao-visual'
    | '/selection-process/$candidateId'
    | '/selection-process/$candidateId/portugues/gravar'
    | '/selection-process/$candidateId/portugues/preview'
    | '/selection-process/$candidateId/questionario/intro'
    | '/selection-process/$candidateId/portugues'
    | '/selection-process/$candidateId/questionario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/interview'
    | '/main'
    | '/entrevista/gravar'
    | '/entrevista/preview'
    | '/logico/intro'
    | '/logico/preview'
    | '/portugues/gravar'
    | '/portugues/preview'
    | '/retencao-visual/teste'
    | '/entrevista'
    | '/logico'
    | '/portugues'
    | '/retencao-visual'
    | '/selection-process/$candidateId'
    | '/selection-process/$candidateId/portugues/gravar'
    | '/selection-process/$candidateId/portugues/preview'
    | '/selection-process/$candidateId/questionario/intro'
    | '/selection-process/$candidateId/portugues'
    | '/selection-process/$candidateId/questionario'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/interview'
    | '/main'
    | '/entrevista/gravar'
    | '/entrevista/preview'
    | '/logico/intro'
    | '/logico/preview'
    | '/portugues/gravar'
    | '/portugues/preview'
    | '/retencao-visual/teste'
    | '/entrevista/'
    | '/logico/'
    | '/portugues/'
    | '/retencao-visual/'
    | '/selection-process/$candidateId/'
    | '/selection-process/$candidateId/portugues/gravar'
    | '/selection-process/$candidateId/portugues/preview'
    | '/selection-process/$candidateId/questionario/intro'
    | '/selection-process/$candidateId/portugues/'
    | '/selection-process/$candidateId/questionario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  InterviewRoute: typeof InterviewRoute
  MainRoute: typeof MainRoute
  EntrevistaGravarRoute: typeof EntrevistaGravarRoute
  EntrevistaPreviewRoute: typeof EntrevistaPreviewRoute
  LogicoIntroRoute: typeof LogicoIntroRoute
  LogicoPreviewRoute: typeof LogicoPreviewRoute
  PortuguesGravarRoute: typeof PortuguesGravarRoute
  PortuguesPreviewRoute: typeof PortuguesPreviewRoute
  RetencaoVisualTesteRoute: typeof RetencaoVisualTesteRoute
  EntrevistaIndexRoute: typeof EntrevistaIndexRoute
  LogicoIndexRoute: typeof LogicoIndexRoute
  PortuguesIndexRoute: typeof PortuguesIndexRoute
  RetencaoVisualIndexRoute: typeof RetencaoVisualIndexRoute
  SelectionProcessCandidateIdIndexRoute: typeof SelectionProcessCandidateIdIndexRoute
  SelectionProcessCandidateIdPortuguesGravarRoute: typeof SelectionProcessCandidateIdPortuguesGravarRoute
  SelectionProcessCandidateIdPortuguesPreviewRoute: typeof SelectionProcessCandidateIdPortuguesPreviewRoute
  SelectionProcessCandidateIdQuestionarioIntroRoute: typeof SelectionProcessCandidateIdQuestionarioIntroRoute
  SelectionProcessCandidateIdPortuguesIndexRoute: typeof SelectionProcessCandidateIdPortuguesIndexRoute
  SelectionProcessCandidateIdQuestionarioIndexRoute: typeof SelectionProcessCandidateIdQuestionarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retencao-visual/': {
      id: '/retencao-visual/'
      path: '/retencao-visual'
      fullPath: '/retencao-visual'
      preLoaderRoute: typeof RetencaoVisualIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugues/': {
      id: '/portugues/'
      path: '/portugues'
      fullPath: '/portugues'
      preLoaderRoute: typeof PortuguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logico/': {
      id: '/logico/'
      path: '/logico'
      fullPath: '/logico'
      preLoaderRoute: typeof LogicoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevista/': {
      id: '/entrevista/'
      path: '/entrevista'
      fullPath: '/entrevista'
      preLoaderRoute: typeof EntrevistaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retencao-visual/teste': {
      id: '/retencao-visual/teste'
      path: '/retencao-visual/teste'
      fullPath: '/retencao-visual/teste'
      preLoaderRoute: typeof RetencaoVisualTesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugues/preview': {
      id: '/portugues/preview'
      path: '/portugues/preview'
      fullPath: '/portugues/preview'
      preLoaderRoute: typeof PortuguesPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portugues/gravar': {
      id: '/portugues/gravar'
      path: '/portugues/gravar'
      fullPath: '/portugues/gravar'
      preLoaderRoute: typeof PortuguesGravarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logico/preview': {
      id: '/logico/preview'
      path: '/logico/preview'
      fullPath: '/logico/preview'
      preLoaderRoute: typeof LogicoPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logico/intro': {
      id: '/logico/intro'
      path: '/logico/intro'
      fullPath: '/logico/intro'
      preLoaderRoute: typeof LogicoIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevista/preview': {
      id: '/entrevista/preview'
      path: '/entrevista/preview'
      fullPath: '/entrevista/preview'
      preLoaderRoute: typeof EntrevistaPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevista/gravar': {
      id: '/entrevista/gravar'
      path: '/entrevista/gravar'
      fullPath: '/entrevista/gravar'
      preLoaderRoute: typeof EntrevistaGravarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection-process/$candidateId/': {
      id: '/selection-process/$candidateId/'
      path: '/selection-process/$candidateId'
      fullPath: '/selection-process/$candidateId'
      preLoaderRoute: typeof SelectionProcessCandidateIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection-process/$candidateId/questionario/': {
      id: '/selection-process/$candidateId/questionario/'
      path: '/selection-process/$candidateId/questionario'
      fullPath: '/selection-process/$candidateId/questionario'
      preLoaderRoute: typeof SelectionProcessCandidateIdQuestionarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection-process/$candidateId/portugues/': {
      id: '/selection-process/$candidateId/portugues/'
      path: '/selection-process/$candidateId/portugues'
      fullPath: '/selection-process/$candidateId/portugues'
      preLoaderRoute: typeof SelectionProcessCandidateIdPortuguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection-process/$candidateId/questionario/intro': {
      id: '/selection-process/$candidateId/questionario/intro'
      path: '/selection-process/$candidateId/questionario/intro'
      fullPath: '/selection-process/$candidateId/questionario/intro'
      preLoaderRoute: typeof SelectionProcessCandidateIdQuestionarioIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection-process/$candidateId/portugues/preview': {
      id: '/selection-process/$candidateId/portugues/preview'
      path: '/selection-process/$candidateId/portugues/preview'
      fullPath: '/selection-process/$candidateId/portugues/preview'
      preLoaderRoute: typeof SelectionProcessCandidateIdPortuguesPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selection-process/$candidateId/portugues/gravar': {
      id: '/selection-process/$candidateId/portugues/gravar'
      path: '/selection-process/$candidateId/portugues/gravar'
      fullPath: '/selection-process/$candidateId/portugues/gravar'
      preLoaderRoute: typeof SelectionProcessCandidateIdPortuguesGravarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  InterviewRoute: InterviewRoute,
  MainRoute: MainRoute,
  EntrevistaGravarRoute: EntrevistaGravarRoute,
  EntrevistaPreviewRoute: EntrevistaPreviewRoute,
  LogicoIntroRoute: LogicoIntroRoute,
  LogicoPreviewRoute: LogicoPreviewRoute,
  PortuguesGravarRoute: PortuguesGravarRoute,
  PortuguesPreviewRoute: PortuguesPreviewRoute,
  RetencaoVisualTesteRoute: RetencaoVisualTesteRoute,
  EntrevistaIndexRoute: EntrevistaIndexRoute,
  LogicoIndexRoute: LogicoIndexRoute,
  PortuguesIndexRoute: PortuguesIndexRoute,
  RetencaoVisualIndexRoute: RetencaoVisualIndexRoute,
  SelectionProcessCandidateIdIndexRoute: SelectionProcessCandidateIdIndexRoute,
  SelectionProcessCandidateIdPortuguesGravarRoute:
    SelectionProcessCandidateIdPortuguesGravarRoute,
  SelectionProcessCandidateIdPortuguesPreviewRoute:
    SelectionProcessCandidateIdPortuguesPreviewRoute,
  SelectionProcessCandidateIdQuestionarioIntroRoute:
    SelectionProcessCandidateIdQuestionarioIntroRoute,
  SelectionProcessCandidateIdPortuguesIndexRoute:
    SelectionProcessCandidateIdPortuguesIndexRoute,
  SelectionProcessCandidateIdQuestionarioIndexRoute:
    SelectionProcessCandidateIdQuestionarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
